feat: Add completed step

diff --git a/.github/workflows/tfc-test-application-modules-apply-enterprise.yaml b/.github/workflows/tfc-test-application-modules-apply-enterprise.yaml
--- a/.github/workflows/tfc-test-application-modules-apply-enterprise.yaml
+++ b/.github/workflows/tfc-test-application-modules-apply-enterprise.yaml
@@ -45,3 +45,17 @@ jobs:
       environment_name: ${{ github.ref_name }}
       tfc_workspace: ${{ inputs.tfc_workspace || vars.tfc_workspace }}
       source_dir: ${{ inputs.source_dir || vars.source_dir }}
+
+  # This is needed because skipped tests are marked as succesfull in GitHub required test, we test here if it was succesfully run and then mark it as such, if it's skipped or fails then it's marked as failed.
+  completed:
+    if: ${{ !cancelled() }}
+    runs-on: ubuntu-latest
+    needs: [terraform-file-changes, deploy]
+    outputs:
+      deploy-result: ${{ needs.deploy.result }}
+    steps:
+      - id: workflow-or-terraform-change
+        if: ${{ (needs.terraform-file-changes.outputs.result == 'false')  || (needs.deploy.result  == 'success') }}
+        run: exit 0
+      - if: failure() || steps.workflow-or-terraform-change.outcome != 'success'
+        run: exit 1
