feat: Add completed step to tf-plan

diff --git a/.github/workflows/tfc-test-application-modules-plan-and-test-enterprise.yaml b/.github/workflows/tfc-test-application-modules-plan-and-test-enterprise.yaml
--- a/.github/workflows/tfc-test-application-modules-plan-and-test-enterprise.yaml
+++ b/.github/workflows/tfc-test-application-modules-plan-and-test-enterprise.yaml
@@ -48,7 +48,23 @@ on:
         required: true
 
 jobs:
+  terraform-file-changes:
+    runs-on: ubuntu-latest
+    # permissions:
+    #   pull-requests: read
+    outputs:
+      result: ${{ steps.terraform-file-changes.outputs.terraform }}
+    steps:
+    - uses: actions/checkout@v4
+    - uses: dorny/paths-filter@v3
+      id: terraform-file-changes
+      with:
+        filters: |
+          terraform:
+            - '**/*.tf'
   build:
+    needs: terraform-file-changes
+    if: ${{ needs.terraform-file-changes.outputs.result == 'true' }}
     concurrency:
       group: ${{ github.ref_name }}
     runs-on: ubuntu-latest
@@ -125,3 +141,17 @@ jobs:
         run: |
           TF_IN_AUTOMATION=true TF_TOKEN_app_terraform_io=${{ secrets.tfc_api_token || secrets.tfc_planner_api_token }} TF_WORKSPACE=${{ inputs.tfc_workspace }} terraform plan
           echo "WARNING: This is a speculative plan. It may not reflect what you see when running terraform apply"
+
+  # This is needed because skipped tests are marked as succesfull in GitHub required test, we test here if it was succesfully run and then mark it as such, if it's skipped or fails then it's marked as failed.
+  completed:
+    if: ${{ !cancelled() }}
+    runs-on: ubuntu-latest
+    needs: [terraform-file-changes, tf-test , tf-plan]
+    outputs:
+      deploy-result: ${{ needs.tf-plan.result }}
+    steps:
+      - id: workflow-or-terraform-change
+        if: ${{ (needs.terraform-file-changes.outputs.result == 'false')  || (needs.tf-plan.result  == 'success')  || (needs.tf-test.result  == 'success')}}
+        run: exit 0
+      - if: failure() || steps.workflow-or-terraform-change.outcome != 'success'
+        run: exit 1
