feat: Bring check improvments to apply

diff --git a/.github/workflows/tfc-test-apply-helper-module-enterprise.yaml b/.github/workflows/tfc-test-apply-helper-module-enterprise.yaml
--- a/.github/workflows/tfc-test-apply-helper-module-enterprise.yaml
+++ b/.github/workflows/tfc-test-apply-helper-module-enterprise.yaml
@@ -8,7 +8,23 @@ on:
         default: 'localstack'
 
 jobs:
+  changes:
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: read
+    outputs:
+      terraform: ${{ steps.changes.outputs.terraform }}
+    steps:
+    - uses: dorny/paths-filter@v3
+      id: changes
+      with:
+        filters: |
+          terraform:
+            - '**/*.tf'
+
   get-matrix-directories:
+    needs: changes
+    if: ${{ needs.changes.outputs.terraform == 'true' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -17,6 +33,7 @@ jobs:
         run: echo "matrix=$(ls | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
+      
   localstack-apply:
     needs: get-matrix-directories
     runs-on: ubuntu-latest
@@ -38,9 +55,21 @@ jobs:
           cd "${{ matrix.folders }}"
           tflocal init
           tflocal apply --auto-approve
+
+  # This is needed because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
+  # Because skipped tests are marked as succesfull in GitHub required test, we test here if it was succesfully run and then mark it as such, if it's skipped or fails then it's marked as failed.
   completed:
-    needs: localstack-apply
+    if: ${{ always() }}
     runs-on: ubuntu-latest
+    needs: [changes, localstack-apply]
     steps:
-      - name: Tests completed # Needed because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
-        run: echo "All tests completed"
+      - run: |
+          if [[ ${{ needs.changes.outputs.terraform }} == "false" ]]
+          then
+            exit 0
+          elif  [[ ${{ needs.localstack-plan.result }} == "success" ]]
+          then
+            exit 0
+          else
+            exit 1
+          fi
